### ISSUE TITLE
Add Urthecast 

### ISSUE THREAD

**Issue by brunosan** [satsummit/landscape#33]
[Feedback from email, registering here]

Consider adding the specs of their product to the graph.

- [ ] Get specs and source: resolution, license, repetition, ...
- [ ] Make PR and include to graph.

**Comment by danlopez00** [comment]
Thanks, Bruno! Our team will provide a merge request, and send over product specs

**Comment by smit1678** [comment]
@danlopez00 Did you have the chance to send over specs? If you want to post here, I can help get these live.

**Comment by kjbrazil** [comment]
Hey guys, wanted to chime in here and provide a handful of resources.

First of all, you can create an Urthecast Platform account here: [developers.urthecast.com/create-account](developers.urthecast.com/create-account).

There you will find full documentation and tools for working with our Earth APIs, of which we currently have six:

- Satellite Tracker: Tracker past, present, and future locations of the ISS, Deimos-1 & 2, and Landsat 8.
- Archive:  A search engine for all the data in the Urthecast Platform.
- Map Tiles: Easiest way to render any imagery on the Urthecast Platform on a map. Offers on-the-fly rendering in RGB, NDVI, NDWI, EVI, and False-color NIR.
- Areas of Interest: Allows for persistent monitoring of points, lines, or polygons on the planet.
- Events - Centralized way to track geospatial events on the Urthecast Platform. (E.g. new imagery available.)
- Ordreing - Offers ability to extract GeoTIFF imagery out of the Archive. Can be done as whole scene or clipped to an AOI.

Our [Satellites & Sensors page](https://developers.urthecast.com/docs/satellites-and-sensors) offers more details about the data in the platform.

Additionally, the [Satellites page](https://www.urthecast.com/enterprise/cameras) on our website offers the details on all the sensors we currently own.

You are more than welcome to add our offerings to the tables and also use our Map Tiles service to improve some of those imagery examples.

Let me know if you need any help getting started.
