### ISSUE TITLE
Add Sentinel 2

### ISSUE THREAD

**Issue by ianschuler** [satsummit/landscape#36]
Let's get Sentinel 2 data in the imagery comparison over Fortaleza as soon as it becomes available. It's currently a dark spot on Sentinel coverage. Continuing to track at http://sentinel-pds.s3-website.eu-central-1.amazonaws.com

![as of 3Feb16](https://www.evernote.com/l/ACOnAJ0pjURMHZqDHkkWl7a6qrxiJqtR8xsB/image.png)

**Comment by ianschuler** [comment]
Looks like there is some new imagery over Fortaleza. Pretty cloudy, but it may be possible to pull out the city - http://sentinel-s2-l1c.s3-website.eu-central-1.amazonaws.com/#tiles/24/M/WA/2016/1/25/0/

**Comment by nbumbarger** [comment]
Sorry if this request has been open for a while- I just had my attention drawn to it.

**Comment by nbumbarger** [comment]
I just noticed this issue followup, sorry for the wait. This Sentinel-2 scene is quite cloudy over Fortaleza, but it's certainly possible to discern that the image fidelity is significantly improved over the Landsat example. Recall that Sentinel-2 offers 10m native resolution in Red, Green, Blue and NIR bands, whereas Landsat needs to rely on pan-sharpening to approximate 15m resolution from its native 30. Sentinel-2 also offers several additional ultraviolet, near and shortwave infrared bands at courser resolution.

https://github.com/satsummit/landscape/pull/44

cc @smit1678 @ianschuler

**Comment by smit1678** [comment]
Deployed in #44
