### ISSUE TITLE
"ESA's Copernicus programme" -> "European Union's Copernicus programme"

### ISSUE THREAD

**Issue by brunosan** [satsummit/landscape#43]
Request via email from the European Commision:

>"The Copernicus programme is a European Union programme and not an ESA programme.  The European Space Agency (ESA) serves as of our partners for the technical implementation. The European Union owns the Sentinel satellites and its data. So we would be grateful, if you could change the text in the table from 'ESA Sentinel 2' to 'EU Sentinel 2' . This goes also for the first bullet point under distribution: Please change ' ESA's Copernicus programme' to 'European Union's Copernicus programme'."

**Comment by nbumbarger** [comment]
Fixed in https://github.com/satsummit/landscape/pull/44

**Comment by brunosan** [comment]
:+1: :heart:
