### ISSUE TITLE
Restructuring and Design Updates 

### ISSUE THREAD

**Issue by ascalamogna** [satsummit/landscape#47]
## Proposing a new structure and outline

As we think about new content, adding new features or other examples, we thought it would be worthwhile to think through a restructure and redesign to help with readability and usability. Circulating my notes and ideas below to the wider community here for any feedback and input. 

---

I've created some new wireframes for the updated structure. I think these updates will allow the site to scale overtime as more content is added. I've tried to also make sure this feels more like a living document and guide. The persistent navigation should allow users to better navigate to the information they are looking for, while the previous and next buttons will guide a newer user through the system in a linear format. 

For reference some of these changes are based on the idea of adding new sections like Examples, Tools for Aspiring Analysts, and reorganize some of the content. The overall goal of any changes are to strike a good balance of separating content while not creating too many subpages. 

Contents:
- Introduction
  - new + planned sensors, table and graphic
  - beyond optical sensors
  - common band combinations
-  Capture
  - Resolution
  - Revisit
  - Sensors
- Analysis
  - Spectral combinations
  - Advanced Analysis
- Distribution
  - Key Concepts
  - Additional Concepts
- Impact
  - Examples
    - Forest and Agriculture
    - Disaster Reduction and Response
    - More examples in International Development
- Tools for Aspiring Analysts

Below are desktop and mobile views of the structure updates. The left navigation will always be open unless you are on mobile where it is hidden under the menu icon. By keeping the navigation exposed we allow the user to always see where they are in the document and also always have options to switch sections. In mobile, we can add breadcrumbs to solve this issue. I think it's important to note that this is a responsive website and not a mobile app and so we're keeping the navigation at the top, as that's where users expect it to be.

![desktop-final](https://cloud.githubusercontent.com/assets/6752098/14575608/e48e6bec-0330-11e6-85e1-313aa8579c1d.png)

![mobile portrait](https://cloud.githubusercontent.com/assets/6752098/14746054/d031766c-087b-11e6-95a5-d56b3f693797.png)

Let me know if you have any feedback, questions or comments!

**Comment by drewbo** [comment]
Implemented
