### ISSUE TITLE
Images are not showing up (links broken?)

### ISSUE THREAD

**Issue by pythagoraswitch** [satsummit/landscape#53]
I haven't looked into the cause yet but the images are not showing up in the interactive leaflet containers.  
example 1
![image](https://cloud.githubusercontent.com/assets/4925075/17030664/7dbe1c50-4f3e-11e6-91ab-13158f1f3202.png)
example 2
![image](https://cloud.githubusercontent.com/assets/4925075/17030677/913400e2-4f3e-11e6-8bfc-55dfa8329b47.png)
example 3
![image](https://cloud.githubusercontent.com/assets/4925075/17030705/b579a1c8-4f3e-11e6-883c-46429de5e3ea.png)

**Comment by drewbo** [comment]
Thanks for the heads-up @pythagoraswitch, looks like we need to update the Mapbox account:
```js
{
  message: "Not Authorized - Invalid Token"
}
```

**Comment by drewbo** [comment]
Should be all set now
