### ISSUE TITLE
Restructuring and Design Updates Preparation

### ISSUE THREAD

**Issue by DylanMoriarty** [satsummit/landscape#55]
Hey folks, I'm about to dive into restructuring the front-end for [Satellites in Global Development (SiGD)](http://landscape.satsummit.io/)

@ascalamogna already set out back in Spring to create a [nifty set of wireframes](https://github.com/satsummit/landscape/issues/47) for the redesign. 

In that thread there are a few dangling threads that I'd like addressed before I hop off the diving board. Namely that I thought it'd be good for our resident sat experts @matthewhanson & @nbumbarger, to review the content and see if there are places we could improve it. 

- Are there sections of SiGD that should be improved, whether that be the written content or the examples provided?
- Are there sections that should be removed?
- Are there features of sat development that you think should be added that aren't there currently?

Also while no one left any feedback in the wireframe thread, it's always welcome as well. It'd be great to sit down with @ricardomestre @ascalamogna if either of you have any further thoughts on the wireframes as is before I start cranking on it.

If you could both consider those questions and offer feedback here, it'd be great to go over it on Monday. Thanks!

@ianschuler

**Comment by drewbo** [comment]
Stale but some updates happened
