### ISSUE TITLE
Mapbox maps over quota

### ISSUE THREAD

**Issue by brunosan** [satsummit/landscape#67]
Maps are broken since the account associated with the token [is over quota](https://a.tiles.mapbox.com/v4/stateofsatellite.ql2i6bt9.json?access_token=pk.eyJ1IjoiYnJ1bm9zYW4iLCJhIjoiY2lxeHg5N2p4MDFyYmZrbWdybWw2eDR6ciJ9.dzFsJgTLWzEeVb8rvhsONw&secure)

```
{"message":"Account over limit."}
```
<img width="958" alt="screen shot 2018-05-16 at 3 51 53 pm" src="https://user-images.githubusercontent.com/434029/40121104-14933d66-5921-11e8-8a1f-63a4027d84b9.png">

**Comment by olafveerman** [comment]
Fixed this, thanks for flagging @brunosan
