### ISSUE TITLE
Add Plausible 

### ISSUE THREAD

**Issue by aboydnw** [satsummit/landscape#91]
We should add Plausible ASAP so we can judge any changes in usage from our upcoming updates

Here is the tag we can use

`<script defer data-domain="landscape.satsummit.io" src="https://plausible.io/js/script.outbound-links.js"></script>`

**Comment by aboydnw** [comment]
@danielfdsilva do you think we should add this quickly to start collecting some baseline metrics?

**Comment by danielfdsilva** [comment]
@aboydnw This is live now

**Comment by aboydnw** [comment]
beautiful, I see the data now too 🙌 

thanks @danielfdsilva ! As we go into any development, let me know if we can use this somehow :)
